### ISSUE TITLE
Необходимо удалить лишние файлы из репозитория

### ISSUE THREAD

**Issue by DamienVStone** [mirrreli/instagtest#2]
Не должно быть в проекте лишних папок и файлов:

[.idea](https://github.com/mirrreli/instagtest/tree/main/.idea)
[Lib/site-packages](https://github.com/mirrreli/instagtest/tree/main/Lib/site-packages)
[Scripts](https://github.com/mirrreli/instagtest/tree/main/Scripts)
[pyvenv.cfg](https://github.com/mirrreli/instagtest/blob/main/pyvenv.cfg)

**Comment by DamienVStone** [comment]
Не забывай привязывать коммиты к задачкам

**Comment by mirrreli** [comment]
В плане давать названия и описание связанное?

Пт, 22 июля 2022 г. в 17:02, Dmitry Nikitin ***@***.***>:
