### ISSUE TITLE
Настройка политики слияния через Pull Request

### ISSUE THREAD

**Issue by DamienVStone** [mirrreli/instagtest#4]
Необходимо заблокировать ветвь main для прямого слияния изменений, оставить разрешение на слияние только через Pull Request

**Comment by mirrreli** [comment]
Не могу найти в настройках такой пункт.

**Comment by DamienVStone** [comment]
Settings -> Branches -> Branch protection rules

**Comment by DamienVStone** [comment]
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule
