### ISSUE TITLE
Изучить инструмент docker compose

### ISSUE THREAD

**Issue by DamienVStone** [mirrreli/instagtest#6]
- Изучить инструмент 
- На основе полученных знаний организовать запуск всех элементов системы через docker compose
- Используя модель ветвления feature branch создать запрос на вытягивание (Pull Request) с готовой фичей

**Comment by mirrreli** [comment]
Добавила. С последним пунктом разобраться не смогла

**Comment by DamienVStone** [comment]
Последний пункт подразумевает, что тобой изучена модель ветвления feature branch. Смысл в том, что напрямую в ветку master вливать изменения не очень хорошо, хочу тебе показать пример как работают в командах. Каждая команда сама определяет подход для работы с репозиторием, но как пример пойдет feature branch, остальное имеет схожие черты.

**Comment by DamienVStone** [comment]
Готовая фича в 3м пункте - это перевод системы на работу с PostgreSQL =) но ты уже это сделала похоже...

**Comment by mirrreli** [comment]
Тогда как раз для этого нужно правило для ветвей? Если да, то, получается, выполнила.
